config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'articles#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'preview', to: 'articles#preview'

  delete 'logout', to: 'sessions#destroy'

  resources :articles, except: [:index] do
    scope module: :articles do
      resources :loves, only: [:create, :destroy]
    end
  end

  resources :users
  resources :categories, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  helper_method :preview

  def index
    @articles = Article.includes(:category, :image).order(vote_count: :desc, updated_at: :desc)
    @top_article = Article.order(vote_count: :desc).first
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Artist was successfully created'
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def preview
    @preview_article = Article.new
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Note was successfuly update'
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted.'
    redirect_to articles_path
  end

  private

  def set_article
    # debugger
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :image_id, :user_id, :category_id, :font_id, :is_private)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.includes(:category, :image).order(vote_count: :desc, updated_at: :desc)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    name = params[:session][:name].downcase
    user = User.find_by(name: name)
    if user
      session[:user_id] = user.id
      flash[:success] = 'Successfully Login'
    else
      flash[:info] = "new username #{name} is registered. "
      user = User.create(name: name)
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<figure>
  <%= image_tag(image_url(article.image)) %>
  <%= link_to category_path(article.category) do%>
    <div class="top__layout">
      <h4>
          <%= article.category.name%>
      </h4>
      <small> <%= pluralize(article.vote_count,"love")%></small>
    </div>
  <% end %>
  <% if loved_article?(article) %>
    <%= link_to article_lofe_path(article,id:love_or_unlove_btn(article).id), method: :delete do%>
    <span class="btn btn-active">
        <%= render 'layouts/love-btn'%>
    </span>
    <% end %>
  <% else %>
    <% if logged_in?%>
      <%= link_to  article_loves_path(article), method: :post do%>
      <span class="btn">
          <%= render 'layouts/love-btn'%>
      </span>
      <% end %>
    <% else%>
      <%= link_to login_path,remote: true,class: "user-login btn" do%>
          <%= render 'layouts/love-btn'%>
      <% end %>
    <% end %>
  <% end %>
  <figcaption><%= article.title%></figcaption>
</figure>

app/views/articles/index.html.erb
<div id="main__layout">
    <section id="header">
        <div class="header">
            <%= image_tag("https://source.unsplash.com/#{@top_article.image.image_url}/1600x600", class:"header__image") %>
            <div class="header__layout">
                <%= link_to category_path(@top_article.category) do%>
                    <div class="header__layout-top">
                        <h4 class="header__layout-top-category">
                            <%= @top_article.category.name%>
                        </h4>
                        <small class="header__layout-top-love"> <%= pluralize(@top_article.vote_count,"love")%></small>
                        <% if loved_article?(@top_article) %>
                                <%= link_to article_lofe_path(@top_article,id:love_or_unlove_btn(@top_article).id), method: :delete do%>
                                <span class="btn btn-active">
                                    <%= render 'layouts/love-btn-big'%>
                                </span>
                                <% end %>
                            <% else %>
                                <% if logged_in?%>
                                    <%= link_to  article_loves_path(@top_article), method: :post do%>
                                    <span class="btn">
                                        <%= render 'layouts/love-btn-big'%>
                                    </span>
                                    <% end %>
                                <% else %>
                                    <%= link_to login_path,remote: true,class: "user-login btn" do%>
                                        <%= render 'layouts/love-btn-big'%>
                                    <% end %>
                                <% end %>
                            <% end %>
                    </div>
                <% end %>
                <div class="header__layout-bottom">
                    <h3 class="header__layout-bottom-title">
                        <%= @top_article.title%>
                    </h3>
                    <p class="header__layout-bottom-content"> <%= @top_article.content%></p>
                </div>
            </div>
        </div>
    </section>
    <div id="columns">
        <% @articles.each do |article|%>
            <% if logged_in? %>
                <%= link_to article_path(article) do%>
                    <%= render '/articles/article', article: article%>
                <%end %>
            <%else%>
                <%= link_to login_path,remote: true,class: "user-login" do%>
                    <%= render '/articles/article', article: article%>
                <%end %>
            <%end%>
        <% end %>
    </div>
</div>

app/views/categories/show.html.erb
<div id="main__layout">
    <section class="user__profile">
        <h4 class="user__profile-name"><%= @category.name.capitalize %></h4>
        <small class="user__profile-notes-count">(<%= pluralize(@category.articles.count,"notes")%>)</small>
    </section>
    <div id="columns">
        <% @articles.each do |article|%>
            <% if logged_in? %>
                <%= link_to article_path(article) do%>
                    <%= render '/articles/article', article: article%>
                <%end %>
            <%else%>
                <%= link_to login_path,remote: true,class: "user-login" do%>
                    <%= render '/articles/article', article: article%>
                <%end %>
            <%end%>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="fixed-top">
  <nav class="inner-header layout-flex flex-space-around">
      <div class="logo layout-flex flex-item-center">
              <h1>
                <%= link_to 'LoveNotes',root_path%>
              </h1>
      </div>
      <div class="page layout-flex flex-item-center flex-space-around">
        <%= link_to 'Home',root_path%>
        <% if logged_in? %>
          <%= link_to 'My Notes',user_path(current_user)%>
          <%= link_to 'Logout',logout_path,method: :delete%>
        <% else %>
            <%= link_to 'Login',login_path,remote: true, class: "user-login"%>
        <% end %>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoveNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

    <link href="https://fonts.googleapis.com/css2?family=Economica:ital,wght@0,400;0,700;1,400;1,700&family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Marck+Script&family=Montez&family=Roboto+Slab:wght@300;500;700&family=Satisfy&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'shared/messages'%>
    <main>
      <%= yield %>
    </main>
    <%= render 'shared/footer'%>
    <%= render 'shared/modal'%>
  </body>
</html>

app/views/shared/_footer.html.erb
  <!-- Site footer -->
<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="left">
            <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by
            <a href="#">Scanfcode</a>.
            </p>
          </div>
          <div class="right">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fab fa-facebook-f"></i></a></li>
              <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fab fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/users/show.html.erb
<div id="main__layout">
    <section class="user__profile">
        <span class="user__profile-circle">
            <%= @user.name.capitalize[0] %>
        </span>
        <h4 class="user__profile-name"><%= @user.name.capitalize %></h4>
        <small class="user__profile-notes-count">(<%= pluralize(@user.articles.count,"notes")%>)</small>
        <%= button_to 'Create A Note',new_article_path,class:"user__profile-btn-create", method: :get%>
    </section>
    <div id="columns">
        <% @articles.each do |article|%>
            <% if logged_in? %>
                <%= link_to article_path(article) do%>
                    <%= render '/articles/article', article: article%>
                <%end %>
            <%else%>
                <%= link_to login_path,remote: true,class: "user-login" do%>
                    <%= render '/articles/article', article: article%>
                <%end %>
            <%end%>
        <% end %>
    </div>
</div>